# Generated by Django 5.1.3 on 2024-11-06 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('preferedGender', models.CharField(choices=[('male', 'Męskie'), ('unisex', 'Uniseks'), ('female', 'Damskie')], max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userEmail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
