# Generated by Django 5.1 on 2024-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='gender',
            field=models.CharField(choices=[('unisex', 'Uniseks'), ('male', 'Męskie'), ('female', 'Damskie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_high',
            field=models.CharField(choices=[('mid', 'Buty typu Mid'), ('low', 'Buty typu Low'), ('high', 'Buty typu High')], max_length=50),
        ),
    ]
