# Generated by Django 5.1.3 on 2024-11-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='preferedGender',
            field=models.CharField(choices=[('unisex', 'Uniseks'), ('female', 'Damskie'), ('male', 'Męskie')], max_length=50),
        ),
    ]
