# Generated by Django 5.1 on 2024-08-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_shoe_gender_alter_shoe_shoe_high'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='shoe',
            options={'verbose_name_plural': 'Shoes'},
        ),
        migrations.AlterField(
            model_name='shoe',
            name='gender',
            field=models.CharField(choices=[('unisex', 'Uniseks'), ('female', 'Damskie'), ('male', 'Męskie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_high',
            field=models.CharField(choices=[('low', 'Buty typu Low'), ('high', 'Buty typu High'), ('mid', 'Buty typu Mid')], max_length=50),
        ),
    ]
