# Generated by Django 5.1.3 on 2024-11-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userdetails_preferedgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='preferedGender',
            field=models.CharField(choices=[('female', 'Damskie'), ('unisex', 'Uniseks'), ('male', 'Męskie')], max_length=50),
        ),
    ]
