# Generated by Django 5.1 on 2024-09-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='gender',
            field=models.CharField(choices=[('female', 'Damskie'), ('male', 'Męskie'), ('unisex', 'Uniseks')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_high',
            field=models.CharField(choices=[('low', 'Buty typu Low'), ('mid', 'Buty typu Mid'), ('high', 'Buty typu High')], max_length=50),
        ),
    ]
