# Generated by Django 5.1.3 on 2024-11-21 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shoe_gender_alter_shoe_shoe_high_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='gender',
            field=models.CharField(choices=[('female', 'Damskie'), ('male', 'Męskie'), ('unisex', 'Uniseks')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='preferedGender',
            field=models.CharField(choices=[('female', 'Damskie'), ('male', 'Męskie'), ('unisex', 'Uniseks')], max_length=50),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=100, null=True)),
                ('item1_variant', models.CharField(max_length=100, null=True)),
                ('item2', models.CharField(max_length=100, null=True)),
                ('item2_variant', models.CharField(max_length=100, null=True)),
                ('item3', models.CharField(max_length=100, null=True)),
                ('item3_variant', models.CharField(max_length=100, null=True)),
                ('item4', models.CharField(max_length=100, null=True)),
                ('item4_variant', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
