# Generated by Django 5.1.3 on 2024-11-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_cart_item1_size_cart_item2_size_cart_item3_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='permissions',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='gender',
            field=models.CharField(choices=[('male', 'Męskie'), ('unisex', 'Uniseks'), ('female', 'Damskie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_high',
            field=models.CharField(choices=[('low', 'Low Top'), ('high', 'High Top'), ('mid', 'Mid Top')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='preferedGender',
            field=models.CharField(choices=[('male', 'Męskie'), ('unisex', 'Uniseks'), ('female', 'Damskie')], max_length=50),
        ),
    ]
