# Generated by Django 5.1.3 on 2024-11-27 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_userdetails_permissions_alter_shoe_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='gender',
            field=models.CharField(choices=[('female', 'Damskie'), ('unisex', 'Uniseks'), ('male', 'Męskie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_high',
            field=models.CharField(choices=[('mid', 'Mid Top'), ('low', 'Low Top'), ('high', 'High Top')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='preferedGender',
            field=models.CharField(choices=[('female', 'Damskie'), ('unisex', 'Uniseks'), ('male', 'Męskie')], max_length=50),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(blank=True, max_length=100, null=True)),
                ('item1_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('item1_size', models.CharField(blank=True, max_length=100, null=True)),
                ('item2', models.CharField(blank=True, max_length=100, null=True)),
                ('item2_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('item2_size', models.CharField(blank=True, max_length=100, null=True)),
                ('item3', models.CharField(blank=True, max_length=100, null=True)),
                ('item3_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('item3_size', models.CharField(blank=True, max_length=100, null=True)),
                ('item4', models.CharField(blank=True, max_length=100, null=True)),
                ('item4_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('item4_size', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_accepted', models.BooleanField(default=False, help_text='Indicates whether the order has been accepted by admin.')),
                ('shipped', models.BooleanField(default=False, help_text='Indicates whether the order has been shipped.')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.address')),
                ('admin_accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_accepted_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
