# Generated by Django 5.1.3 on 2024-11-27 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_shoe_gender_alter_shoe_shoe_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.userdetails'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='gender',
            field=models.CharField(choices=[('unisex', 'Uniseks'), ('male', 'Męskie'), ('female', 'Damskie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='preferedGender',
            field=models.CharField(choices=[('unisex', 'Uniseks'), ('male', 'Męskie'), ('female', 'Damskie')], max_length=50),
        ),
    ]
