# Generated by Django 5.1.3 on 2024-11-29 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_shoe_gender_alter_shoe_shoe_high_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='shoe_high',
            field=models.CharField(choices=[('low', 'Low Top'), ('high', 'High Top'), ('mid', 'Mid Top')], max_length=50),
        ),
        migrations.CreateModel(
            name='UsersQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50)),
                ('user_firstName', models.CharField(max_length=50)),
                ('user_lastName', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=350)),
                ('admin_solved', models.BooleanField(default=False, help_text='Indicates whether the question has been solved by admin.')),
                ('admin_solved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_solved_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
