# Generated by Django 5.1.3 on 2024-11-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_cart_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='admin_accepted',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates whether the order has been accepted by admin.', null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipped',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates whether the order has been shipped.', null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='gender',
            field=models.CharField(choices=[('unisex', 'Uniseks'), ('female', 'Damskie'), ('male', 'Męskie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_high',
            field=models.CharField(choices=[('mid', 'Mid Top'), ('low', 'Low Top'), ('high', 'High Top')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='preferedGender',
            field=models.CharField(choices=[('unisex', 'Uniseks'), ('female', 'Damskie'), ('male', 'Męskie')], max_length=50),
        ),
    ]
