# Generated by Django 5.1.3 on 2024-11-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_orders_admin_accepted_alter_orders_shipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='admin_accepted',
            field=models.BooleanField(default=False, help_text='Indicates whether the order has been accepted by admin.'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipped',
            field=models.BooleanField(default=False, help_text='Indicates whether the order has been shipped.'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='gender',
            field=models.CharField(choices=[('female', 'Damskie'), ('unisex', 'Uniseks'), ('male', 'Męskie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_high',
            field=models.CharField(choices=[('mid', 'Mid Top'), ('high', 'High Top'), ('low', 'Low Top')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='preferedGender',
            field=models.CharField(choices=[('female', 'Damskie'), ('unisex', 'Uniseks'), ('male', 'Męskie')], max_length=50),
        ),
    ]
